file=open('anketa.txt','w')
fio=input('ФИО')
data=input('Дата рождения')
city=input('Город')
place=input('Место учебы')
print('ФИО',fio)
file.write('ФИО '+fio+'\n')
print('Дата рождения', data)
file.write('Дата рождения '+data+'\n')
print('Город', city)
file.write('Город '+city+'\n')
print('Место учебы', place)
file.write('Место учебы '+place+'\n')
file.close()
